class AccountEvent:
    REGISTER         = "account.register"
    REGISTER_FAILED  = "account.register.failed"
    REGISTER_REPLAY = "account.register.replayed"
    LOGIN            = "account.login"
    LOGIN_FAILED     = "account.login.failed"
    LOGIN_CHALLENGE_ISSUED = "account.login.challenge.issued"
    SESSION_REFRESHED = "account.session.refresh"
    SESSION_REFRESH_FAILED = "account.session.refresh.failed"
    SESSION_LIST_VIEWED = "account.session.list.viewed"
    LOGOUT           = "account.logout"
    LOGOUT_FAILED = "account.logout.failed"
    PIN_STATUS_VIEWED = "account.pin.status.viewed"
    PIN_SET          = "account.pin.set"
    PIN_CHECK_OK     = "account.pin.check.success"
    PIN_CHECK_FAILED = "account.pin.check.failed"
    PASSWORD_CHANGE_OK     = "account.password.change.success"
    PASSWORD_CHANGE_FAILED = "account.password.change.failed"
    PROFILE_VIEWED         = "account.profile.viewed"
    PROFILE_UPDATED        = "account.profile.updated"
    EMAIL_VERIFY_SENT      = "account.email.verify.sent"
    EMAIL_VERIFY_CONFIRMED = "account.email.verify.confirmed"
    EMAIL_VERIFY_FAILED = "account.email.verify.failed"
    OTP_VERIFIED           = "account.otp.verified"
    OTP_VERIFY_FAILED      = "account.otp.verify.failed"
    MFA_ENROLLED           = "account.mfa.enrolled"
    MFA_ENROLL_FAILED = "account.mfa.enroll.failed"
    MFA_VERIFIED           = "account.mfa.verified"
    MFA_VERIFY_FAILED      = "account.mfa.failed"
    MFA_RECOVERY_REGENERATED = "account.mfa.recovery_codes.regenerated"

class WalletEvent:
    BALANCE_VIEWED   = "wallet.balance.viewed"
    BALANCE_CREDITED = "wallet.balance.credited"
    BALANCE_CREDIT_FAILED = "wallet.balance.credit.failed"
    PAYMENT_INITIATED = "wallet.payment.initiated"
    PAYMENT_INITIATION_FAILED = "wallet.payment.initiation.failed"
    PAYMENT_CONFIRMED = "wallet.payment.confirmed"
    PAYMENT_CONFIRM_FAILED = "wallet.payment.confirm.failed"
    PAYMENT_IDEMPOTENCY_MISMATCH = "wallet.payment.idempotency_mismatch"
    PAYMENT_INSUFFICIENT_FUNDS = "wallet.payment.insufficient_funds"
    PAYMENT_OWNER_MISMATCH = "wallet.payment.owner_mismatch"
    PAYMENT_REQUEST_LIST_VIEWED = "wallet.payment_request.list.viewed"
    PAYMENT_REQUEST_CREATED = "wallet.payment_request.created"
    PAYMENT_REQUEST_CREATE_FAILED = "wallet.payment_request.create.failed"
    PAYMENT_REQUEST_APPROVED = "wallet.payment_request.approved"
    PAYMENT_REQUEST_APPROVE_FAILED = "wallet.payment_request.approve.failed"
    PAYMENT_REQUEST_DECLINED = "wallet.payment_request.declined"
    PAYMENT_REQUEST_DECLINE_FAILED = "wallet.payment_request.decline.failed"
    PAYMENT_REQUEST_OWNER_MISMATCH = "wallet.payment_request.owner_mismatch"
    TRANSACTION_CHAIN_VERIFICATION_FAILED = "wallet.transaction.chain_verification_failed"
    TRANSACTION_RECORD_MISMATCH = "wallet.transaction.record_mismatch"
    TRANSACTION_RECEIPT_MISMATCH = "wallet.transaction.receipt_mismatch"
    TRANSACTION_BALANCE_MISMATCH = "wallet.transaction.balance_mismatch"
    TRANSACTION_HISTORY_VIEWED = "wallet.transaction_history.viewed"
    SUPERVISORY_APPROVAL_LIST_VIEWED = "wallet.supervisory_approval.list.viewed"
    SUPERVISORY_APPROVAL_CREATED = "wallet.supervisory_approval.created"

class RecipientEvent:
    RECIPIENT_LIST_VIEWED = "recipient.list.viewed"
    RECIPIENT_SEARCH_PERFORMED = "recipient.search.performed"
    RECIPIENT_ADDED   = "recipient.added"
    RECIPIENT_ADD_FAILED = "recipient.add.failed"
    RECIPIENT_REMOVED = "recipient.removed"
    RECIPIENT_REMOVE_FAILED = "recipient.remove.failed"

class NotificationEvent:
    NOTIFICATION_LIST_VIEWED = "notification.list.viewed"
    NOTIFICATION_READ = "notification.read"
