# Generated by Django 5.2.7 on 2026-05-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicaluser_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
