# Generated by Django 5.2.7 on 2026-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicaluser_balance_historicaluser_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
