# Generated by Django 5.2.7 on 2026-05-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_security_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='mfa_enrollment_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='mfa_totp_seed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enrollment_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_totp_seed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
