from datetime import timedelta


MIN_PAYMENT_CENTS = 1
MAX_PAYMENT_CENTS = 5000
MIN_FUNDING_CENTS = 100
MAX_FUNDING_CENTS = 50000

FIRST_TIME_LARGE_TRANSACTION_THRESHOLD_CENTS = 2500
HIGH_FREQUENCY_TRANSACTION_THRESHOLD = 5
PAYMENT_REQUEST_EXPIRY = timedelta(hours=72)
