from datetime import timedelta


EMAIL_VERIFICATION_TTL = timedelta(hours=24)
AUTH_FLOW_TTL = timedelta(minutes=10)
SESSION_TTL = timedelta(hours=8)

RECOVERY_CODE_LENGTH = 16
RECOVERY_CODE_COUNT = 8

LOCKOUT_WINDOW = timedelta(minutes=15)
LOCKOUT_DURATION = timedelta(minutes=30)
FAILED_LOGIN_NOTIFICATION_THRESHOLD = 3
LOCKOUT_ATTEMPT_THRESHOLD = 5

RECIPIENT_DEFAULT_PAGE_SIZE = 20
USER_SEARCH_MIN_QUERY_LENGTH = 2
MFA_ISSUER_NAME = "SecureWallet"
